Django_one/Protwo/Protwo/urls.py
from django.contrib import admin
from django.urls import path,include
from app_two import views

urlpatterns = [
    path('',include('app_two.urls')),
    path('admin/', admin.site.urls),
    path('index/',views.index,name = 'index'),
]

Django_one/Protwo/app_two/urls.py
from django.urls import path
from app_two import views

# TEMPLATE TAGGING
app_name = 'app_two'

urlpatterns = [
    path('users/',views.users,name = 'user'),
    path('registration/',views.registration,name = 'register'),
    path('login/',views.user_login,name = 'login'),
    path('logout/',views.user_logout,name = 'logout'),
    path('special/',views.special,name = 'special'),
]

Django_one/Protwo/app_two/models.py
from distutils.command.upload import upload
from pyexpat import model
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #ADDITIONAL
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank =True)
    
    def __str__(self):
        return self.user.username

Django_one/Protwo/app_two/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
# from django.contrib.auth.forms import Authentication
from django.contrib.auth.models import User
from app_two.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
        

Django_one/Protwo/app_two/views.py
from django.shortcuts import render
from app_two.forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# # Create your views here.

def index(request):
    return render(request,'app_two/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in successfully !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def registration(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if profile_form.is_valid() and user_form.is_valid() :
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'app_two/registration.html',{ 'user_form': user_form, 'profile_form': profile_form, 'registered': registered })

def users(request):
    return render(request,"app_two/users.html")
    
def user_login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print(f"Username : {username} and Password : {password}")
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request,'app_two/login.html',{})

Django_one/Protwo/templates/app_two/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <div class="collapse navbar-collapse">
                <a  class="navbar-brand mb-0 h1" href="#">Matrix</a>
                <a  class="navbar-brand" href="{% url 'index' %}">Home</a>
                <a  class="navbar-brand" href="{% url 'app_two:register' %}">Register</a>

                {% if user.is_authenticated %}
                <a  class="navbar-brand" href="{% url 'app_two:logout' %}">Logout</a>
                {% else %}
                <a  class="navbar-brand" href="{% url 'app_two:login' %}">Login</a>
                {% endif %}

                <input style="width: 25%;" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
        </div>
    </nav>
    
    {% block body_block %}
    {% endblock %}
</body>
</html>

Django_one/Protwo/templates/app_two/index.html
{% extends "app_two/basic.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome , </h1>
</div>

{% endblock %}

Django_one/Protwo/templates/app_two/login.html
{% extends "app_two/basic.html" %}
{% load static %}
{% block body_block %}


<div class="jumbotron" >
    <h1>Login Page</h1>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="username" >

        <label for="password">Password</label>
        <input type="text" name="password">

        <input type="submit" value="submit" name="submit">
    </form>
</div>

{% endblock %}

Django_one/Protwo/templates/app_two/registration.html
{% extends "app_two/basic.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the form</h3>
    
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>

{% endblock %}

Django_one/Protwo/templates/app_two/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Users Info</title>
</head>
<body>
    <div class="container">
        <h1>Please Sign_up Here</h1>

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit" >
        </form>
    </div>
</body>
</html>